name: Build & Test Web

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test Coverage
        run: pnpm test:coverage

      - name: Check Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "web/coverage/lcov.info"
          min_coverage: 80

      # - name: "Report Coverage"
      #   if: always()
      #   uses: davelosert/vitest-coverage-report-action@v2
      #   with:
      #     working-directory: web
      #     json-summary-path: coverage/coverage-summary.json
      #     json-final-path: coverage/coverage-final.json
